# Generated by Django 4.0.1 on 2022-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='document.Tag'),
        ),
    ]
